version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["docker/Dockerfile"]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = ["nodejs"]

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/CyberdyneHQ/monitors-test-repo"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "ansible"